#include QMK_KEYBOARD_H

enum custom_keycodes {
  QUOT_ENTER = SAFE_RANGE
};

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */


const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_planck_mit(
            KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
            KC_CAPS, KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, LT(0, KC_QUOT),
            KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, KC_MINS,
            KC_LCTL, MO(2), KC_LALT, KC_LGUI, MO(3), KC_SPC, KC_LBRC, LT(1,KC_RBRC), KC_LEFT, KC_DOWN, KC_GRV
        ),
	[1] = LAYOUT_planck_mit(
            KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_BSPC,
            KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_TRNS,
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_MSTP, KC_MUTE, KC_MPRV, KC_MPLY, KC_MNXT, RGB_VAI, KC_TRNS,
            KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, RGB_VAD, RGB_MOD
            ),
	[2] = LAYOUT_planck_mit(
            KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
            KC_CAPS, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_TRNS,
            KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_UP, KC_SLSH,
            KC_LCTL, KC_NO, KC_LALT, KC_DEL, KC_PGDN, KC_SPC, KC_PGUP, KC_NO, KC_LEFT, KC_DOWN, KC_RGHT
        ),
	[3] = LAYOUT_planck_mit(
            QK_BOOT, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_MINS, KC_EQL, KC_BSLS,
            KC_TRNS, LGUI(KC_1), LGUI(KC_2), LGUI(KC_3), LGUI(KC_4), LGUI(KC_5), KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_SCLN, KC_ENT,
            KC_TRNS, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_QUOT, KC_WH_U,
            KC_TRNS, MO(2), KC_LALT, KC_LGUI, KC_NO, KC_SPC, KC_RBRC, MO(1), KC_LEFT, KC_DOWN, KC_WH_D
        )
};

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case LT(0,KC_QUOT):
            if (!record->tap.count && record->event.pressed) {
                tap_code(KC_ENT); // Intercept hold function to send Ctrl-X
                return false;
            }
            return true;             // Return true for normal processing of tap keycode
    }
    return true;
}

/*
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
        case KC_QUOT:
            if (record->tap.count && record->event.pressed) {
                tap_code(KC_QUOT); // Intercept tap function to send Ctrl-C
            } else if (record->event.pressed) {
                tap_code(KC_ENT); // Intercept hold function to send Ctrl-V
            }
            return false;
    }
    return true;
}
*/

/*
bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  static uint16_t my_hash_timer;

  switch (keycode) {
    case QUOT_ENTER:
      if(record->event.pressed) {
        my_hash_timer = timer_read();
        register_code(KC_ENT); // Change the key to be held here
      } else {
        unregister_code(KC_ENT); // Change the key that was held here, too!
        if (timer_elapsed(my_hash_timer) < TAPPING_TERM) {
            register_code(KC_QUOT);
           //SEND_STRING("#"); // Change the character(s) to be sent on tap here
        }
      }
      return false; // We handled this keypress
  }
  return true; // We didn't handle other keypresses
}
*/

#if defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
const uint16_t PROGMEM encoder_map[][NUM_ENCODERS][NUM_DIRECTIONS] = {

};
#endif // defined(ENCODER_ENABLE) && defined(ENCODER_MAP_ENABLE)
